package com.example.flightbooking.repository;

import com.example.flightbooking.model.Admin;
import org.springframework.data.jpa.repository.JpaRepository;
import java.util.Optional;

public interface AdminRepository extends JpaRepository<Admin, Long> {

    /**
     * Finds an Admin entity by their username.
     * This is a derived query, automatically generated by Spring Data JPA.
     *
     * @param username The username of the admin.
     * @return An Optional containing the Admin if found, otherwise an empty Optional.
     */
    Optional<Admin> findByUsername(String username);
}