package com.example.flightbooking.model;

import jakarta.persistence.*;
import lombok.Data;
import java.time.LocalDateTime;

@Entity
@Data
public class Booking {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private Long flightId;

    private Long customerId;

    private LocalDateTime bookingTime;

    private String seatNumber;

    private double totalFare;

    // Constructors, getters, and setters are generated by Lombok's @Data annotation
    // You can add custom methods here if needed
}